# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Tom Henderson
tagline:          What I've worked out so far...
description:      Base theme for Jekyll themes by @mdo.
url:              http://tom-henderson.github.io

author:
  name:           Tom Henderson
  url:            http://tom-henderson.github.io

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/tom-henderson/tom-henderson.github.io
